### ISSUE TITLE
About the number of inputs of RIMs.

### ISSUE THREAD

**Issue by zhangzx-sjtu** [anirudh9119/RIMs#1]
Hi, it is very kind of you to release the implementations of RIMs. 

I have read your code and discovered that in `event_based/rnn_models.py` and `event_based/rnn_models_wiki.py` (which are imported in the training scripts), the variable `num_blocks_in` is restricted to `1`  due to the following line of code:

`num_blocks_in = [1 for i in topk]`

(as in Line #64 in `rnn_models.py` and Line #58 in `rnn_models_wiki.py`)

If I understand it correctly, is the number of input elements at each time step (i.e. the number of rows of the x_t matrix in the paper) always set to 1 in the experiments?

If not, then which variable represents the number of input elements at each time step?

Thanks! Greatly appreciated it if you could help :-)

**Comment by alexmlamb** [comment]
I believe it's 1 input element at each time step.  In principle though, if your data had some kind of structure per time-step, it should be possible to use many input elements.

**Comment by zhangzx-sjtu** [comment]
Got it. I am just asking to validate my guess :)
