### ISSUE TITLE
Experiment setting for training baseline LSTM model in copying task

### ISSUE THREAD

**Issue by lizhenstat** [anirudh9119/RIMs#5]
Hi, thanks for releasing the code. 

I have one question on reproducing baseline LSTM model result in copying task.

I was trying to run 
```python
bash experiment_copying_lstm.sh 600
```
The hidden number of unit is set to 600 according to the paper, the function to load the LSTM model is 
the following:
```python
model = rnn_mod(args.model, inp_dim, out_dim, args.emsize, args.nhid,
                        args.nlayers, args.dropout, args.tied,
                        use_cudnn_version=args.cudnn,
                        use_adaptive_softmax=args.adaptivesoftmax, cutoffs=args.cutoffs).to(device)
```
I read the copying_data.py and figured the generated data dimension is supposed to be [n_data, n_train+20, batch_size]
My question is what is the following  two parameter values:  **inp_dim** and **out_dim** to reproducing results in Table1(Left)?

Thanks for your time and any help would be appreciated!
Best wishes

**Comment by anirudh9119** [comment]
Sorry, both the values should be ntokens, ntokens (they both are defined in the train_copying.py). Let me know if it works.

**Comment by lizhenstat** [comment]
@anirudh9119  Hi, thanks for your quick reply!

I edit inp_dim and out_dim to **ntokens=20**  and change train_len=50 and test_len=200(default in RIM scenario)
Besides, I change the following default parameters
(1) change  **discrete_input=False**  to **discrere_input=True** in RNNModel in baseline_lstm_model_adding.py, 
If not, the following error occur.
```python
RuntimeError: size mismatch, m1: [70 x 64], m2: [20 x 600] at /opt/conda/conda-bld/pytorch_1556653183467/work/aten/src/THC/generic/THCTensorMathBlas.cu:268
```

(2) add **model.train()** in train_copying.py
```python
if i % args.log_interval == 0 and i > 0:
    test_loss = evaluate_(eval_copy_x, eval_copy_y)
    model.train() # add this line
```
otherwise it will give out the following error:
```python
RuntimeError: cudnn RNN backward can only be called in training mode
```
(It is werid since running the RIM example(experiment_copying.sh) did not give out this error)

Now, it the code can run!
Is this modification right? Thanks a lot
